spring.application.name=smartbiz-backend

# =========================================================
# DATABASE MYSQL LOCAL
# =========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/smartbiz?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0806
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =========================================================
# MAIL SENDER (Gmail SMTP)
# =========================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anhtai80605@gmail.com
spring.mail.password=lzbx pyim hlcs plev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================================================
# JWT CONFIGURATION
# =========================================================
jwt.secret=smartbiz-secret-key-for-jwt-token-generation-and-validation-2024
jwt.expiration=86400000

#Oauth2 Configuration
spring.security.oauth2.client.registration.google.client-id=862422979623-e84p40tn6lorde6dh3mbj5l9r2vc8e3f.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Frontend URL that receives oauth2 result (token, role, email, ...)
app.oauth2.authorized-redirect-uri=http://localhost:3000/owner/dashboard
